name:  deployment
# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main # Replace with your branch name
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 195.35.20.88
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: | 
            su user-apps
            whoami
            pwd
